name: Cypress CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Env
      run: |
        echo "${{ secrets.DJANGO_SECRET_KEY2 }}" | base64 -d > _backend/_backend/secrets.py

    - name: Start Vue server
      run: |
        cd duolango-frontend
        npm install -g @vue/cli
        npm install
        npm run serve

    - name: Wait for Vue server to start
      run: |
        while true; do
          curl --head --fail http://localhost:8080 && break
          sleep 1
        done

    - name: Start Django server
      run: |
        cd _backend
        python manage.py runserver

    - name: Wait for Django server to start
      run: |
        while true; do
          curl --head --fail http://localhost:8000 && break
          sleep 1
        done

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        start: npm run serve
      env:
        CYPRESS_baseUrl: http://localhost:8080

